#ifndef COMPLEXITYEXPERIMENTEXP_GLOBAL_H
#define COMPLEXITYEXPERIMENTEXP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPLEXITYEXPERIMENTEXP_LIBRARY)
#  define COMPLEXITYEXPERIMENTEXPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPLEXITYEXPERIMENTEXPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VECTORGRADIENTWITHSWAPEXP_GLOBAL_H
